# env:
#   TZ: "America/New_York"

httpRoute:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  parentRefs:
    - name: default
      namespace: nginx-gateway
      # sectionName: https  # depends on your gateway's listener names
  hostnames:
    - grocy.example.com
  httpRedirect:
    enabled: true

# persistence:
#   storageClass: longhorn
